const companies = [
     { name: "Microsoft", rating: 92, sector: "Software" },
     { name: "Salesforce", rating: 91, sector: "Software" },
     { name: "SAP", rating: 90, sector: "Software" },
     { name: "Unilever", rating: 85, sector: "Consumer Goods" },
     { name: "Intel", rating: 78, sector: "Semiconductors" },
     { name: "Cisco", rating: 88, sector: "Tech" },
     { name: "NVIDIA", rating: 75, sector: "Semiconductors" },
     { name: "ASML", rating: 77, sector: "Semiconductors" },
     { name: "Apple", rating: 76, sector: "Tech Hardware" },
     { name: "IBM", rating: 83, sector: "Tech" },
     { name: "Adobe", rating: 84, sector: "Software" },
     { name: "Sony", rating: 59, sector: "Electronics" },
     { name: "Qualcomm", rating: 58, sector: "Semiconductors" },
     { name: "Texas Instruments", rating: 58, sector: "Semiconductors" },
     { name: "Visa", rating: 74, sector: "Finance" },
     { name: "Mastercard", rating: 74, sector: "Finance" },
     { name: "L'Oréal", rating: 73, sector: "Beauty" },
     { name: "Equinix", rating: 68, sector: "Tech Infrastructure" },
     { name: "Danaher", rating: 69, sector: "Healthcare Tech" },
     { name: "Medtronic", rating: 67, sector: "Healthcare Tech" },
     { name: "Eli Lilly", rating: 73, sector: "Healthcare" },
     { name: "Sanofi", rating: 73, sector: "Healthcare" },
     { name: "Roche", rating: 73, sector: "Healthcare" },
     { name: "Novartis", rating: 73, sector: "Healthcare" },
     { name: "Pfizer", rating: 70, sector: "Healthcare" },
     { name: "Johnson & Johnson", rating: 55, sector: "Healthcare" },
     { name: "Siemens", rating: 57, sector: "Industrial" },
     { name: "Honeywell", rating: 56, sector: "Manufacturing" },
     { name: "Nike", rating: 39, sector: "Apparel" },
     { name: "Adidas", rating: 39, sector: "Apparel" },
     { name: "Samsung", rating: 55, sector: "Electronics" },
     { name: "PepsiCo", rating: 38, sector: "Food & Bev" },
     { name: "Coca-Cola", rating: 38, sector: "Food & Bev" },
     { name: "Nestlé", rating: 36, sector: "Food & Bev" },
     { name: "Mondelez", rating: 35, sector: "Food & Bev" },
     { name: "Starbucks", rating: 37, sector: "Food & Bev" },
     { name: "Diageo", rating: 50, sector: "Alcohol" },
     { name: "Estée Lauder", rating: 51, sector: "Beauty" },
     { name: "UPS", rating: 52, sector: "Logistics" },
     { name: "FedEx", rating: 52, sector: "Logistics" },
     { name: "Target", rating: 34, sector: "Retail" },
     { name: "CVS Health", rating: 54, sector: "Healthcare" },
     { name: "Verizon", rating: 54, sector: "Telecom" },
     { name: "Disney", rating: 53, sector: "Media" },
     { name: "Amazon", rating: 30, sector: "Retail" },
     { name: "Walmart", rating: 29, sector: "Retail" },
     { name: "Tesla", rating: 32, sector: "Automotive" },
     { name: "BYD", rating: 19, sector: "Automotive" },
     { name: "McDonald's", rating: 28, sector: "Food Service" },
     { name: "Home Depot", rating: 33, sector: "Retail" },
     { name: "Lowe's", rating: 33, sector: "Retail" },
     { name: "Kraft Heinz", rating: 27, sector: "Food & Bev" },
     { name: "JPMorgan Chase", rating: 56, sector: "Finance" },
     { name: "Goldman Sachs", rating: 55, sector: "Finance" },
     { name: "Morgan Stanley", rating: 57, sector: "Finance" },
     { name: "BlackRock", rating: 54, sector: "Finance" },
     { name: "American Express", rating: 58, sector: "Finance" },
     { name: "Tencent", rating: 19, sector: "Tech" },
     { name: "ExxonMobil", rating: 18, sector: "Energy" },
     { name: "Chevron", rating: 18, sector: "Energy" },
     { name: "Rio Tinto", rating: 17, sector: "Mining" },
     { name: "Boeing", rating: 52, sector: "Aerospace" },
     { name: "Philip Morris International", rating: 12, sector: "Tobacco" },
     { name: "Bridgestone", rating: 18, sector: "Manufacturing" },
     { name: "Tata Motors", rating: 17, sector: "Automotive" },
     { name: "ICBC", rating: 10, sector: "Finance" },
     { name: "China Construction Bank", rating: 10, sector: "Finance" },
     { name: "Agricultural Bank of China", rating: 10, sector: "Finance" },
     { name: "Ferrari", rating: 50, sector: "Automotive" },
     { name: "Prada", rating: 28, sector: "Luxury" },
     { name: "Hermès", rating: 49, sector: "Luxury" },
];